---
title: "Coding Practice Assignment"
author: "Yearin Kim"
date: "2022-11-17"
output: html_document
---

## Front Matter

```{r}
#clean up the environment
rm(list = ls())

#libraries
library(readxl)
library(tidyverse)

#load excel files
crime <- read_excel("C:/Users/kzy51/Desktop/SoDA 496/crime_rates.xlsx")

immigration <- read_excel("C:/Users/kzy51/Desktop/SoDA 496/immigration.xlsx")

gdp <- read_excel("C:/Users/kzy51/Desktop/SoDA 496/GDP.xlsx")

unemployment <- read_excel("C:/Users/kzy51/Desktop/SoDA 496/unemployment.xlsx")
```

## View all collected datasets
```{r}
crime 
immigration
gdp
unemployment
```

## Cleaning 

### cleaning gdp 

```{r}
#rename of confusing column
gdp <- gdp %>% rename(StateCode = GeoCode, State = GeoName)

gdp
```

### Cleaning immigration 

```{r}
#get rid of unnecessary column
immigration <- immigration %>% select(-TotalPopulation, -ImmigrationShareofTotalStatePopulation)

#rename of long column
immigration <- immigration %>% rename(ImmigrationPop = ImmigrationPopulation)

immigration
```

### Cleaning crime 

```{r}
#get rid of unnecessary column
crime <- crime %>% select(-Jail, -TotalPrisoner)

#rename of long column
crime <- crime %>% rename(StatePop = StatePopulation, Crime = TotalViolentCrime, Rape = TotalRape, Murder = TotalMurder, Robbery = TotalRobbery, Assult = TotalAssult)

crime
```

### Cleaning unemployment

```{r}
#rename of long and confusing column
unemployment <- unemployment %>% rename(Education = EducationAttainment, Unemployment = TotalUnemployment, Native = NationalUnemployment, Foreign = ForeignUnemployment)

#get rid of unnecessary column
unemployment <- unemployment %>% select(-Country, -CountryCode, -Sex)

unemployment
```

## Merging 

### Merging crime and immigration 

```{r}
dataset <- crime %>% inner_join(immigration, by = c("State" = "State", "StateCode" = "StateCode", "Year" = "Year"))

dataset
```

### Merging dataset and gdp 

```{r}
dataset <- dataset %>% inner_join(gdp, by = c("State" = "State", "StateCode" = "StateCode", "Year" = "Year"))

dataset
```

### Merging dataset and unemployment

```{r}
dataset <- dataset %>% inner_join(unemployment, by = c("Year" = "Year"))

dataset
```

## Data Preparation for regression analysis

```{r}
# generate a variable for each immigration rate and crime rate
dataset <- dataset %>% mutate(ImmigrationRate = ImmigrationPop / StatePop,
                              CrimeRate = Crime / StatePop)

dataset
```

## Cleaning dataset

```{r}
#deal with missing data
dataset <- dataset %>% na.omit(dataset)
```

## Run a simple regression analysis

```{r}
model <- lm(ImmigrationRate ~ CrimeRate, data = dataset)

summary(model)
```